### ISSUE TITLE
vreji te mifra

### ISSUE THREAD

**Issue by este-rs** [mungojelly/mlevlaste#1]
mi tolzau lo nu pilno lo o'yrygy vreji i ri jai jonsimri'a lo lerpinsle i na'e lifri fa lo nu tai pilno
i lo mydy vreji cu xagmau i ku'i ji'a go'oi jonsimri'a i ja'e bo na mapti
i ru'a pilno lo tyxyty vreji i sampu veirco'e i la gitxab na ba cizra arco lo veirpau

i e'u tai ganzu:

```
ni'o zo <valsi> noi gismu/lujvo/cmevla/cmavo be zo <selma'o>:
[ro da poi lerpinsle zo'u da se krasi re kutybu'i i bo da se nilcla li me'i 71]
  (velski...)
[kunti lerpinsla]
```

i mu'a

```
[........1.........2.........3.........4.........5.........6.........7]
ni'o zo besto noi gismu
  i zo besto mabla valsi i terbrimei li 45 a li 44 (to lo 44 moi cu
  na'e zvati i ti'e ki'u bo rinka lo nu malfu'a toi) i ke'u ze'e ku no
  jbopre cu se xi ci vo besto

ni'o zo zdalatukuuerpo'alergiiamakarenaketukuuerpo'espadarle'alergiia-
kosabuuenazdalatukuuerpo'alergiiamakarena'eimakarena noi fu'ivla
  oi
```

**Comment by este-rs** [comment]
ni'o ta'o
mi ba'e _ca_ bregau lo tyxyty panra fau lo nu do djica tu'a ri

**Comment by este-rs** [comment]
ca'e kargau za'ei

**Comment by mungojelly** [comment]
.i su'a mi nelci la .org. .i ku'i .ie lo nu pilno fi tau MVS cu na'e se snada .i la'a nai so'i prenu cu nelci lo nu pilno la .org. .i ji'a TXT na'e banzu pe'i .i lo go'i cu sampydu'e .i .au ganzu banzu se ri'a lo nu pilno frili je lo nu melbi .i XML .a'u nai jai cumki .i ku'i milxe po'o lo ka plixau .i je mutce pe'i lo ka fegli .i zabna sai! da'i sai! sai!! fa lo nu pilno lo jbobau lo nu ganzu .i lo proga cu na'e ku'i zasti je cu kakne lo nu galfi lo jbobauselsmu lo melbi ja lo plixau .i ja'o zabna fa lo nu pilno la'o .gy. s-expressions .gy. .i milxe lo kamfrili fa lo nu zbasu lo tutci be lo nu galfi lo sy. zei terge'a lo XML mu'a terge'a .i mi to'e nelci lo da'i nu XML ralju .i XML fegli je'u je cu jai na se kakne lo prenu fai lo nu tcidu .i .e'u ma'a finti lo sy. zei terge'a tarmi se va'u MVS

**Comment by este-rs** [comment]
.u'i ru'e .i sa'u pu zu ku loi sampli cu pilno lo tyxyty vreji .i je lo nu melgau cu sampu sai! .i sa'u banzu

**Comment by mungojelly** [comment]
.i mi na jimpe .i li'a pilno .ei ASCII .i ku'i lo ji'a te morna cu plixau fi lo nu galfi fi lo vrici noi plixau .i mu'a djica se'o lo nu lo proga cu kakne lo nu valsi sisku .i lo proga cu nitcu lo nu kakne lo nu djuno lo du lo velski cu kuspe ma kau .i sampu je vajni mupli .i so'i drata cu cumki je cu poi'i mi djica lo nu troci ke'a
